### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jp-bennett** [chrismyers2000/MeshAdv-Pi-Hat#1]
Hey, this design looks super interesting. What license is this under? Is it kosher for other people to fab these, rather than going through the Etsy store?

**Comment by chrismyers2000** [comment]
Hi Jonathan,
I don’t know much about licensing, but people are free to build these for personal use. But I’d prefer not for commercial purposes, ie for profit, at least while I’m running the Etsy store. Hope that answers your question 👍

**Comment by chrismyers2000** [comment]
License has been added to the project
